#-----------(PATTERN NUMBER 1)------------
#  *****
#  *****
#  *****
#  *****
#  *****
for x in range (1,6):
	for y in range (1,6):
		print ("*", end= "")
	print()




#------------(PATTERN NUMBER 2)------------
#  11111
#  22222
#  33333
#  44444
#  55555
for x in range (1,6):
	for y in range (1,6):
		print (x, end= "")
	print()




#------------(PATTERN NUMBER 3)------------
#  12345
#  12345
#  12345
#  12345
#  12345
for x in range (1,6):
	for y in range (1,6):
		print (y, end= "")
	print()




#------------PATTERN NUMBER 4------------
#  55555 
#  44444
#  33333
#  22222
#  11111
for x in range (5,0,-1):
	for y in range (5,0,-1):
		print (x, end= "")
	print()




#------------PATTERN NUMBER 5------------
#  54321
#  54321
#  54321
#  54321
#  54321
for x in range (5,0,-1):
	for y in range (5,0,-1):
		print (y, end= "")
	print()
